### ISSUE TITLE
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', lumen/src/main.rs:297:9

### ISSUE THREAD

**Issue by notes365** [naim94a/lumen#19]
**Describe the bug**
```sh
root@user123:~/lumen/lumen/bin/release# ./lumen -c config.toml
 2021-02-04T07:14:42.313Z INFO  lumen > starting private lumen server...
 2021-02-04T07:14:42.339Z INFO  lumen > starting http api server on 0.0.0.0:8082
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', lumen/src/main.rs:297:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```
**To Reproduce**
CONFIG.tomL
```tomL
[lumina]
# address that lumen will listen on for IDA to connect to
bind_addr = "0.0.0.0:1234"
# indicates if TLS should be used for connections, if true the `lumina.tls` section is required.
use_tls = false
# server display name; appears in IDA output window
server_name = "lumen"

# only required when `use_tls` is set to true.
[lumina.tls]
# Specify the server's certificate. 
# Clients connecting to the server must match this certificate.
# If the certificate is password protected, the password can be specified in the `PKCSPASSWD` environment variable.
server_cert = "path/to/server_crt"

[database]
# Specifies a postgresql connection string. All variables can be found here: https://docs.rs/tokio-postgres/0.6.0/tokio_postgres/config/struct.Config.html
connection_info = "host=127.0.0.1 user=my_new_lunmne password=my_new_lunmne "
# Sets if the database connection should be made using TLS.
use_tls = false
# If the database requires a secure connection, paths to server-ca and client-id certificates can be set here:
server_ca = "db_ca.pem"
client_id = "db_id.p12"

# comment out this section to disable api server
# api server allows to query the database for comments by file or function hash.
[api_server]
bind_addr = "0.0.0.0:8082"
```

**Server (please complete the following information):**
 - OS:  Debian 10
 - Architecture: x86_64
